---
pod_network_cidr: 192.168.10.0/24
k8s_master_ip: 192.168.86.111
ansible_user: bcladmin
pod_network_manifest_file: https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
bac_manifest_file: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml
