---
- name: Get the join command from the master node
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Set the join command
  set_fact:
    join_command: "{{ join_command.stdout_lines[0] }}"